/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ArticleUpdate = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Opt(IDL.Text),
});
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'published' : IDL.Bool,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArticle' : IDL.Func([IDL.Text, ArticleUpdate], [], []),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'getAllSlugsAdmin' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getArticleById' : IDL.Func([IDL.Nat], [Article], ['query']),
  'getArticleBySlug' : IDL.Func([IDL.Text], [Article], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPublicArticleBySlug' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Article)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllArticlesAdmin' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'listPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'publishArticle' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchArticlesByTag' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'updateArticle' : IDL.Func([IDL.Nat, ArticleUpdate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ArticleUpdate = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Opt(IDL.Text),
  });
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'published' : IDL.Bool,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArticle' : IDL.Func([IDL.Text, ArticleUpdate], [], []),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'getAllSlugsAdmin' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getArticleById' : IDL.Func([IDL.Nat], [Article], ['query']),
    'getArticleBySlug' : IDL.Func([IDL.Text], [Article], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPublicArticleBySlug' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Article)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllArticlesAdmin' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'listPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'publishArticle' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchArticlesByTag' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
    'updateArticle' : IDL.Func([IDL.Nat, ArticleUpdate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };